### ISSUE TITLE
Document Outline does not scroll to the headings on click

### ISSUE THREAD

**Issue by asianindexing** [AngeloFaella/DocumentOutline#2]
Thank you very much for this wonderful library. I am facing some issues while installing it. DO generates outline beautifully but when I click on any heading, it does not scroll to the headings properly. Here is a live link. 

https://tocs.asianindexing.com/chapter.php?id=1681210093508_56113558&title=Chapter+1%3A+Life+and+Services

Moreover, it is leaving an icons of bars at the end of the page. 

![image](https://user-images.githubusercontent.com/130546558/231400278-c53f3f32-d7ed-4da0-b9fa-c5e8c4dbbb6c.png)

Any solution please.

**Comment by AngeloFaella** [comment]
> 

Hi, thanks for the feedback, I see the problem. 
Probably it's related to the `offsetTop` property of the elements wich gives the position relative to the offsetParent and not the absolute position in the page. 
I'll fix thi asap.

**Comment by asianindexing** [comment]
Still the first problem of scrolling persist. I have updated links of JS and CSS files. Perhaps anything is wrong at my end?  Although it is not the right thread to ask but is it possible that outline's sidebar only appears when there are <h...> tags are available in source code. Sometimes we do not know whether there will be headings in the article or not.

**Comment by AngeloFaella** [comment]
> Still the first problem of scrolling persist. I have updated links of JS and CSS files. Perhaps anything is wrong at my end? Although it is not the right thread to ask but is it possible that outline's sidebar only appears when there are <h...> tags are available in source code. Sometimes we do not know whether there will be headings in the article or not.

1. If you used https://cdn.jsdelivr.net/gh/AngeloFaella/DocumentOutline@latest/DocumentOutline.js probably you're still seeing the v1.0 because of the jsdeliver cache. Try with https://cdn.jsdelivr.net/gh/AngeloFaella/DocumentOutline@1.1/DocumentOutline.js (same thing for CSS)
2. Yes, outline is based on the heading tags. If there are not `h` tags there is no way fo the library to understand the document structure

**Comment by asianindexing** [comment]
Thank you, it finally worked. 

2. Perhaps I failed to communicate my message properly. I was thinking that if there are not h tags available in the document then sidebar of document outline should not appear at all. I mean you can check the following link where is no heading in the document but still the outline is appearing. 

https://tocs.asianindexing.com/chapter.php?id=1681210093508_56113557&title=Preface

thank you for your time.
